[package]
name = "raytrace"
version = "0.1.0"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"
random = "0.12.2"

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "benchmarks"
harness = false
path = "src/benchmarks.rs"
